theme = "snazzy"

[editor.indent-guides]
render = true
character = "╎"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = true